### PR TITLE
Add new error for "Violation Check Constraint"

### PR DESCRIPTION
**Pull request by anilsenay**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

Added 23514 pgerrcode support

### User Case Description

Detailed here: https://github.com/go-gorm/gorm/pull/6992

### CODE REVIEW

**Comment by anilsenay** [comment]
This PR requires to merging https://github.com/go-gorm/gorm/pull/6992
After https://github.com/go-gorm/gorm/pull/6992 merged, this pr must be updated

**Comment by anilsenay** [comment]
hey @jinzhu can you take a look?

**Comment by anilsenay** [comment]
> hey @jinzhu can you take a look?

+up

(sorry for bothering you but I want to use this feature in my project 😄)

**Review by a631807682 — COMMENTED** [review]
Can we add the doc link in comment? like [mysql](https://github.com/go-gorm/mysql/blob/master/error_translator.go#L9)

https://www.postgresql.org/docs/current/errcodes-appendix.html

**Review by a631807682 — APPROVED** [review]

**Comment by anilsenay** [comment]
> Can we add the doc link in comment? like [mysql](https://github.com/go-gorm/mysql/blob/master/error_translator.go#L9)
> 
> https://www.postgresql.org/docs/current/errcodes-appendix.html

done 👍

**Comment by anilsenay** [comment]
@a631807682 if there is no pr to merge, could you add tag as v1.5.8 👉 👈

**Pull request merged**
