### PR TITLE
fix: retract v1.5.5

### PR DESCRIPTION
**Pull request by black-06**
- [X] Do only one thing
- [X] Non breaking API changes
- [X] Tested

### What did this pull request do?

#247, only delete tag v1.5.5 is not enough.
If we accept this mr, we need to publish v1.5.6 to retract v1.5.5 (& v1.5.6)

### CODE REVIEW

**Comment by jinzhu** [comment]
Can you publish the v1.5.6 tag？

**Comment by black-06** [comment]
I don't known how to only publish tag....
I only known I can publish a new release with new tag...

**Comment by J-Rocke** [comment]
@black-06 I think publishing a new release with the new tag is fine. It could also help to explain what happened to people running into this. From the go module side publishing the git tag without a github release is the same as doing a release with the tag.

**Comment by J-Rocke** [comment]
On the commandline you checkout the branch/commit you want to tag and then run: `git tag v1.5.6` to create the tag and then `git push refs/tags/v1.5.6` to push it to github.

**Comment by black-06** [comment]
> On the commandline you checkout the branch/commit you want to tag and then run: `git tag v1.5.6` to create the tag and then `git push refs/tags/v1.5.6` to push it to github.

yes I known if i push the git tag to github，it will create a tag without release.

But what surprised me was that 1.5.5 wasn't pushed by me, it seemed like it was automatically generated, or someone else did it on the page

**Comment by J-Rocke** [comment]
Sorry i misundestood your question. 
I would assume someone else did push the tag. 
Maybe you can check some log in github to find out who pushed it.  
Or the person who deleted the tag maybe knows since github shows who pushed which tag.

**Comment by black-06** [comment]
> Sorry i misundestood your question. I would assume someone else did push the tag. Maybe you can check some log in github to find out who pushed it. Or the person who deleted the tag maybe knows since github shows who pushed which tag.

I deleted the tag, but that tag shows that I pushed it, just like https://github.com/go-gorm/mysql/releases/tag/v1.5.3.
But I know I didn't...

**Comment by J-Rocke** [comment]
Yeah that is strange and you should figure out why that happened. 
Is there any reason to not publish the v1.5.6 now?

**Comment by black-06** [comment]
> Yeah that is strange and you should figure out why that happened. Is there any reason to not publish the v1.5.6 now?

Aha, jinzhu manually pushed the tag.

Okay, I publish it now.

**Pull request merged**
