### PR TITLE
add USING ?::? to `AlterColumn`

### PR DESCRIPTION
**Pull request by warren830**
### What did this pull request do?

Add USING ?::? to AlterColumn
Without this, it will report error as I described in the issue #104 

### User Case Description

We used migrator to change column data type

### CODE REVIEW

**Review by a631807682 — COMMENTED** [review]
LGTM if column without default value.
Maybe we need to add conditions, use `Using` when no implicit (automatic) cast and change the `defalut value`

**Comment by warren830** [comment]
> LGTM if column without default value. Maybe we need to add conditions, use `Using` when no implicit (automatic) cast and change the `defalut value`

Sounds great, I will modify it and submit again

**Comment by warren830** [comment]
> 

I did some shallow research, it's hard to add conditions. Cause there are too many data types.
time <-> varchar,
int <-> varchar
longtext <-> int, varchar
and so on

**Comment by a631807682** [comment]
I don't know whether `Using` has side effects. If not, we can drop default value first when type changes and add it after completion. We can also judge whether to execute the above process through the error code.

**Comment by warren830** [comment]
> I don't know whether `Using` has side effects. If not, we can drop default value first when type changes and add it after completion. We can also judge whether to execute the above process through the error code.

It's a better way to execute the above process according to the error code. If it's ok, I can do it

**Comment by Gilwe** [comment]
it is still broken.
if the column is of part of the partition definition you'll get `ERROR: cannot alter type of column named in partition key (SQLSTATE 42P16)`

**Pull request merged**
