### PR TITLE
refactor: distinguish between Unique and UniqueIndex

### PR DESCRIPTION
**Pull request by black-06**
- [X] Do only one thing
- [X] Non breaking API changes
- [X] Tested

### What did this pull request do?

See https://github.com/go-gorm/gorm/issues/6381.

tested with https://github.com/go-gorm/gorm/pull/6386

### CODE REVIEW

**Review by a631807682 — APPROVED** [review]
Depends on gorm's PR

**Comment by jasonchuan** [comment]
we need to  revert the  https://github.com/go-gorm/postgres/pull/195   relative code first, both in  postgress and gorm.

**Comment by black-06** [comment]
> we need to  revert the  https://github.com/go-gorm/postgres/pull/195   relative code first, both in  postgress and gorm. @black-06 

because its breaking change？
But we have to do/fix this sooner or later

**Comment by jasonchuan** [comment]
ok let's  try to fix it

**Comment by black-06** [comment]
> ok let's try to fix it

yes I'm doing 😰

**Pull request merged**
